# Site settings
title: Adrian's Profile
email: hello@wheelhouse.io
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages"
url: "http://wheehouseio.github.io"
twitter_username: WheelhouseIO
github_username:  wheelhouseio
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index